import os

import repo

def ref_resolve(repository, ref):
    # recursively dereference symbolic refs (refs that point to other refs)
    # this allows HEAD -> refs/heads/master -> commit-sha chain
    path = repo.repo_file(repository, ref)
    if not os.path.isfile(path):
        return None
    with open(path, 'r') as fp:
        data = fp.read()[:-1]
    if data.startswith("ref: "):
        return ref_resolve(repository, data[5:])
    else:
        return data

def ref_list(repository, path=None):
    if not path:
        path = repo.repo_dir(repository, "refs")
    ret = dict()
    for f in sorted(os.listdir(path)):
        can = os.path.join(path, f)
        if os.path.isdir(can):
            ret[f] = ref_list(repository, can)
        else:
            ret[f] = ref_resolve(repository, can)
    return ret

def ref_create(repository, ref_name, sha):
    with open(repo.repo_file(repository, "refs/" + ref_name), 'w') as fp:
        fp.write(sha + "\n")

def branch_get_active(repository):
    with open(repo.repo_file(repository, "HEAD"), "r") as f:
        head = f.read()
    if head.startswith("ref: refs/heads/"):
        return(head[16:-1])
    else:
        return False

def show_ref(repository, refs, with_hash=True, prefix=""):
    # recursively display reference tree structure (tags, branches, remotes)
    # matches git show-ref output format
    if prefix:
        prefix = prefix + '/'
    for k, v in refs.items():
        if type(v) == str and with_hash:
            print (f"{v} {prefix}{k}")
        elif type(v) == str:
            print (f"{prefix}{k}")
        else:
            show_ref(repository, v, with_hash=with_hash, prefix=f"{prefix}{k}")

def tag_create(repository, name, ref, create_tag_object=False):
    # create git tag: either lightweight (just a ref) or annotated (full object with metadata)
    # lightweight tags are simple pointers to commits; annotated tags are full objects
    # lazy import to avoid top-level cycle: objects imports refs
    import objects
    sha = objects.object_find(repository, ref)
    if create_tag_object:
        tag = objects.GitTag()
        tag.kvlm = dict()
        tag.kvlm[b'object'] = sha.encode()
        tag.kvlm[b'type'] = b'commit'
        tag.kvlm[b'tag'] = name.encode()
        tag.kvlm[b'tagger'] = b'Wyag <wyag@example.com>'
        tag.kvlm[None] = b"A tag generated by wyag, which won't let you customize the message!\n"
        tag_sha = objects.object_write(tag, repository)
        ref_create(repository, "tags/" + name, tag_sha)
    else:
        ref_create(repository, "tags/" + name, sha)
