import repo
import objects

def show_ref(repository, refs, with_hash=True, prefix=""):
    # recursively display reference tree structure (tags, branches, remotes)
    # matches git show-ref output format
    if prefix:
        prefix = prefix + '/'
    for k, v in refs.items():
        if type(v) == str and with_hash:
            print (f"{v} {prefix}{k}")
        elif type(v) == str:
            print (f"{prefix}{k}")
        else:
            show_ref(repository, v, with_hash=with_hash, prefix=f"{prefix}{k}")

def tag_create(repository, name, ref, create_tag_object=False):
    # create git tag: either lightweight (just a ref) or annotated (full object with metadata)
    # lightweight tags are simple pointers to commits; annotated tags are full objects
    sha = objects.object_find(repository, ref)
    if create_tag_object:
        tag = objects.GitTag()
        tag.kvlm = dict()
        tag.kvlm[b'object'] = sha.encode()
        tag.kvlm[b'type'] = b'commit'
        tag.kvlm[b'tag'] = name.encode()
        tag.kvlm[b'tagger'] = b'Wyag <wyag@example.com>'
        tag.kvlm[None] = b"A tag generated by wyag, which won't let you customize the message!\n"
        tag_sha = objects.object_write(tag, repository)
        repo.ref_create(repository, "tags/" + name, tag_sha)
    else:
        repo.ref_create(repository, "tags/" + name, sha)
